name: R-CMD-check
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Install dependencies
        run: |
          install.packages(c('devtools','roxygen2'))
      - name: Build and check
        run: |
          R CMD build .
          R CMD check eventviz_0.1.0.tar.gz --as-cran